#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRAutomation.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRAutomation")]
	public partial class AutomationDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AutomationDataDataContext() : 
				base(global::HRAutomation.DAL.Properties.Settings.Default.HRAutomationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AutomationDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutomationDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutomationDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutomationDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InterfaceRecord> InterfaceRecords
		{
			get
			{
				return this.GetTable<InterfaceRecord>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InterfaceRecord")]
	public partial class InterfaceRecord
	{
		
		private int _RecordID;
		
		private string _PerformedBy;
		
		private string _VendorName;
		
		private string _VendorFileName;
		
		private System.Data.Linq.Binary _HrSystemFile;
		
		private string _HrSystemFileName;
		
		private System.Data.Linq.Binary _EncryptedFile;
		
		private string _EncryptedFileName;
		
		private string _Message;
		
		private bool _WasTest;
		
		private System.DateTime _DateOfAction;
		
		public InterfaceRecord()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerformedBy", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PerformedBy
		{
			get
			{
				return this._PerformedBy;
			}
			set
			{
				if ((this._PerformedBy != value))
				{
					this._PerformedBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this._VendorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorFileName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string VendorFileName
		{
			get
			{
				return this._VendorFileName;
			}
			set
			{
				if ((this._VendorFileName != value))
				{
					this._VendorFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrSystemFile", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HrSystemFile
		{
			get
			{
				return this._HrSystemFile;
			}
			set
			{
				if ((this._HrSystemFile != value))
				{
					this._HrSystemFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrSystemFileName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HrSystemFileName
		{
			get
			{
				return this._HrSystemFileName;
			}
			set
			{
				if ((this._HrSystemFileName != value))
				{
					this._HrSystemFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncryptedFile", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary EncryptedFile
		{
			get
			{
				return this._EncryptedFile;
			}
			set
			{
				if ((this._EncryptedFile != value))
				{
					this._EncryptedFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncryptedFileName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EncryptedFileName
		{
			get
			{
				return this._EncryptedFileName;
			}
			set
			{
				if ((this._EncryptedFileName != value))
				{
					this._EncryptedFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WasTest", DbType="Bit NOT NULL")]
		public bool WasTest
		{
			get
			{
				return this._WasTest;
			}
			set
			{
				if ((this._WasTest != value))
				{
					this._WasTest = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfAction", DbType="DateTime NOT NULL")]
		public System.DateTime DateOfAction
		{
			get
			{
				return this._DateOfAction;
			}
			set
			{
				if ((this._DateOfAction != value))
				{
					this._DateOfAction = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
