//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _HRAutomation {
    
    
    public partial class contact {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new _HRAutomation.resources.global.master.HrAuto Master {
            get {
                return ((_HRAutomation.resources.global.master.HrAuto)(base.Master));
            }
        }
    }
}
